Vagrant.configure("2") do |config|
  # Nodo de control Ansible
  config.vm.define "control" do |control|
    control.vm.box = "ubuntu/bionic64"
    control.vm.network "private_network", ip: "192.168.56.2"
    
    control.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    # Provisión para instalar Ansible en el nodo de control
    control.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y ansible
    SHELL
  end

  # Nodo gestionado
  config.vm.define "node" do |node|
    node.vm.box = "ubuntu/bionic64"
    node.vm.network "private_network", ip: "192.168.56.3"
    
    node.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end

    # Configuración de SSH para que el nodo de control pueda gestionar el nodo
    node.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y openssh-server
    SHELL
  end
end