Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  
  # Red privada con IP fija
  config.vm.network "private_network", ip: "192.168.56.2"
  
  # Reenvío del puerto 8080 del host al puerto 80 de la máquina virtual
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Configuración de recursos de hardware
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end
end