Vagrant.configure("2") do |config|
  (2..4).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.box = "bento/ubuntu-23.10"
      node.vm.network "private_network", ip: "192.168.56.#{i}"
      
      # Configuración de recursos
      node.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
      end

      # Provisión para instalar SSH
      node.vm.provision "shell",run: "once", inline: <<-SHELL
        apt-get update
        apt-get install -y openssh-server
        systemctl restart sshd
      SHELL
    end
  end
end