Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  
  # Configuración de red privada con IP fija
  config.vm.network "private_network", ip: "192.168.56.2"
  
  # Sincronización de carpetas entre host y máquina virtual
  config.vm.synced_folder "C:/Users/victo/Downloads", "/home/vagrant/prueba"
  
  # Configuración de recursos de hardware
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"  # 4 GB de memoria
    vb.cpus = 4         # 4 CPUs
  end

  # Reenvío de puertos para acceder a servicios en la máquina virtual
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 3306, host: 3307
end