Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  
  # Configuración de red privada
  config.vm.network "private_network", ip: "192.168.56.2"
  
  # Configuración de recursos de hardware
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  # Provisión para configurar SSH al iniciarse la máquina (solo se ejecuta una vez)
  config.vm.provision "shell", run: "once" do |s|
    s.inline = <<-SHELL
      # Actualizar e instalar el servidor SSH
      apt-get update
      apt-get install -y openssh-server

      # Configurar el servidor SSH para aceptar conexiones externas
      sed -i 's/#Port 22/Port 22/' /etc/ssh/sshd_config
      sed -i 's/^#*PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
      systemctl restart sshd
    SHELL
  end
end