Vagrant.configure("2") do |config|
  # Configuración de la primera máquina: Servidor Web
  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/bionic64"
    web.vm.hostname = "web-server"
    web.vm.network "private_network", ip: "192.168.56.2"
    
    # Configuración de recursos para el servidor web
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 1
    end
    
    # Reenvío de puerto para acceder al servidor web desde el host
    web.vm.network "forwarded_port", guest: 80, host: 8080
  end

  # Configuración de la segunda máquina: Servidor de Base de Datos
  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/bionic64"
    db.vm.hostname = "db-server"
    db.vm.network "private_network", ip: "192.168.56.3"
    
    # Configuración de recursos para el servidor de base de datos
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 1
    end
    
    # Provisión para instalar MySQL en el servidor de base de datos
    db.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y mysql-server
    SHELL
  end
end