Vagrant.configure("2") do |config|
  # Definir la box base
  config.vm.box = "ubuntu/bionic64"
  
  # Configurar el tamaño del disco
  config.disksize.size = "30GB" # Tamaño deseado
  
  # Configurar la red privada
  config.vm.network "private_network", ip: "192.168.56.2"
  
  # Configurar los recursos de hardware
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end
end